# Generated by Django 5.0.9 on 2024-11-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='task_priority',
            field=models.CharField(choices=[('-2', '-2'), ('-1', '-1'), ('0', '0'), ('1', '1'), ('2', '2')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.TextField(blank=True, default='DEFAULT'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(default='DEFAULT', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='task_tag',
            field=models.ManyToManyField(to='task.tag'),
        ),
    ]
