# Generated by Django 5.0.9 on 2024-11-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_task_completed_task_task_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_tag',
        ),
        migrations.AddField(
            model_name='task',
            name='task_due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
