# Generated by Django 5.0.9 on 2024-11-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_task_task_tag_task_task_due_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_tags',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
